# Generated by Django 5.2.4 on 2025-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='baixa', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente')], default='pendente', max_length=25)),
            ],
        ),
    ]
